### ISSUE TITLE
Support for media library

### ISSUE THREAD

**Issue by ChristopherLMiller** [kwinyyyc/strapi-plugin-wysiwsg-react-md-editor#1]
IS there any chance we can get built-in support for inserting images from the media library?

**Comment by kwinyyyc** [comment]
@ChristopherLMiller there is an office guide https://strapi.io/blog/how-to-change-the-default-wysiwy-to-quill-editor adding the media library inside the wysiwyg component for html editor.

I would give it a try to see if that could fit in md editor as well.
