### ISSUE TITLE
TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by totalolage** [kwinyyyc/strapi-plugin-wysiwsg-react-md-editor#2]
Installing this plugin and attempting to edit an entity with a rich text field causes this error:

```
TypeError: Cannot read property 'length' of null
    at e (http://localhost:1337/admin/main.b97a0402.chunk.js:1:2632541)
```

I took a quick look through the codebase and can't find where `.length` is being used.

**Comment by kwinyyyc** [comment]
May I know which strapi version are you using?

**Comment by totalolage** [comment]
Strapi v3.6.1, Node v14.16.1
Now that you mention it, it might be the node version. I'll try it.
