### ISSUE TITLE
Styles don't apply to preview

### ISSUE THREAD

**Issue by dpavloff** [kwinyyyc/strapi-plugin-wysiwsg-react-md-editor#5]
After installing plugin it appears as expected, there are editor and preview view, but no styles apply to preview window.

**Specs:**

- Strapi: 4.1.3
- Node: v12.22.12

**Expected behaviour:**
MD styles apply to text when either applying them by explicitly writing them, or when using the control buttons.

**Actual behaviour:**
<img width="784" alt="image" src="https://user-images.githubusercontent.com/23011754/165509542-08dbf4a7-38c3-475c-ba22-b5724adcc5eb.png">

**UPD:**
There seems to be a reset css package that conflicts with the plugin's styles. By looking into build files, you can find the styles that nullify react-md-editor's styles.

<img width="486" alt="Screen Shot 2022-04-27 at 14 37 54" src="https://user-images.githubusercontent.com/23011754/165510580-ab630576-d4fe-470a-b213-0a7107877334.png">

<img width="461" alt="Screen Shot 2022-04-27 at 14 38 03" src="https://user-images.githubusercontent.com/23011754/165510590-8b55162d-d30d-48e2-ab70-34b6a51bec63.png">

**6228.1856e3ee.chunk:**
<img width="1127" alt="Screen Shot 2022-04-27 at 14 38 23" src="https://user-images.githubusercontent.com/23011754/165510599-6cf3e194-8916-4db6-a83c-af126cec7c8a.png">

**Comment by kwinyyyc** [comment]
@dpavloff  thanks for reporting the issue, yes seems like the style is overridden by reset css.
Added the react-md-editor preview css file in the [latest release](https://github.com/kwinyyyc/strapi-plugin-wysiwsg-react-md-editor/releases/tag/v4.1.2) which has higher specificity. It solves the issue.
